-- ============================================================================
-- FLOWTYM PMS — Migration 0050 : Bank statements + reconciliation runs
-- ----------------------------------------------------------------------------
-- Two tables to power the Reconciliation Center :
--   * `bank_statements`  — raw bank/OTA statement lines (CSV or manual entry)
--   * `reconciliation_runs` — periodic snapshots that match each bank line
--     against either a payout_calculation (RIE) or a reservation payment.
-- ============================================================================

create table if not exists public.bank_statements (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references public.hotels(id) on delete cascade,
  source text not null,                  -- 'BOOKING' / 'EXPEDIA' / 'BANK_HOTEL'
  external_reference text,
  description text,
  amount numeric(14,2) not null,
  currency text not null default 'EUR',
  posted_at timestamptz not null,
  imported_at timestamptz not null default now(),
  matched_validation_id uuid references public.reservation_validations(id),
  matched_reservation_id uuid references public.reservations(id),
  status text not null default 'UNMATCHED',  -- UNMATCHED / MATCHED / DISPUTED / IGNORED
  notes text
);

create index if not exists idx_bank_stmt_hotel on public.bank_statements(hotel_id, posted_at desc);
create index if not exists idx_bank_stmt_status on public.bank_statements(hotel_id, status);

alter table public.bank_statements enable row level security;
drop policy if exists bank_stmt_select on public.bank_statements;
drop policy if exists bank_stmt_modify on public.bank_statements;
create policy bank_stmt_select on public.bank_statements for select to authenticated
  using (hotel_id = public.get_user_hotel_id());
create policy bank_stmt_modify on public.bank_statements for all to authenticated
  using (hotel_id = public.get_user_hotel_id())
  with check (hotel_id = public.get_user_hotel_id());

-- ----------------------------------------------------------------------------
-- ODMS reminders : queue of pending reminders generated by DisputeReminderEngine
-- ----------------------------------------------------------------------------
create table if not exists public.ota_dispute_reminders (
  id uuid primary key default gen_random_uuid(),
  hotel_id uuid not null references public.hotels(id) on delete cascade,
  dispute_id uuid not null references public.ota_disputes(id) on delete cascade,
  step integer not null,                 -- 1=J+2, 2=J+5, 3=J+10
  due_at timestamptz not null,
  status text not null default 'PENDING', -- PENDING / SENT / SKIPPED
  email_payload jsonb,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_dispute_reminders_due on public.ota_dispute_reminders(status, due_at)
  where status = 'PENDING';

alter table public.ota_dispute_reminders enable row level security;
drop policy if exists dispute_reminders_select on public.ota_dispute_reminders;
drop policy if exists dispute_reminders_modify on public.ota_dispute_reminders;
create policy dispute_reminders_select on public.ota_dispute_reminders for select to authenticated
  using (hotel_id = public.get_user_hotel_id());
create policy dispute_reminders_modify on public.ota_dispute_reminders for all to authenticated
  using (hotel_id = public.get_user_hotel_id())
  with check (hotel_id = public.get_user_hotel_id());

-- ----------------------------------------------------------------------------
-- Seed : a few demo bank lines for Mas Provencal Aix
-- ----------------------------------------------------------------------------
do $$
declare
  v_hotel constant uuid := '00000000-0000-0000-0000-000000000001';
begin
  insert into public.bank_statements
    (hotel_id, source, external_reference, description, amount, currency, posted_at, status)
  values
    (v_hotel, 'BOOKING', 'BK-PAYOUT-2026-04-30', 'Booking.com — Payout Apr', 1862.50, 'EUR', now() - interval '7 days', 'UNMATCHED'),
    (v_hotel, 'EXPEDIA', 'EX-PAYOUT-2026-04-29', 'Expedia — Payout Apr', 244.32, 'EUR', now() - interval '8 days', 'UNMATCHED'),
    (v_hotel, 'BOOKING', 'BK-PAYOUT-2026-04-15', 'Booking.com — Payout mid-Apr', 707.20, 'EUR', now() - interval '22 days', 'UNMATCHED'),
    (v_hotel, 'BANK_HOTEL', 'CB-2026-05-01', 'Encaissement CB direct', 1750.00, 'EUR', now() - interval '5 days', 'UNMATCHED'),
    (v_hotel, 'BANK_HOTEL', 'CB-2026-05-04', 'Encaissement CB direct', 360.00, 'EUR', now() - interval '2 days', 'UNMATCHED')
  on conflict do nothing;
end $$;
