import { ReservationFormData } from '../components/modals/ReservationFormModal';

// ─────────────────────────────────────────────────────────────────────────────
// Revenue Calendar metric types (used by usePlanningMetrics hook)
// ─────────────────────────────────────────────────────────────────────────────

export interface DayMetric {
  /** ISO date string YYYY-MM-DD */
  dateStr: string;
  /** Number of rooms with a reservation spanning this day */
  occupiedRooms: number;
  /** Total available rooms */
  availableRooms: number;
  /** Occupancy rate 0-100 */
  occupancyRate: number;
  /** Total revenue generated by reservations present on this day */
  revenue: number;
  /** Average Daily Rate = revenue / max(1, occupiedRooms) */
  adr: number;
  /** Revenue Per Available Room = revenue / max(1, availableRooms) */
  revpar: number;
  /** Number of reservations checking in on this day */
  arrivals: number;
  /** Number of reservations checking out on this day */
  departures: number;
  /** Number of cancelled reservations with check_in on this day */
  cancellations: number;
}

export interface MonthMetric {
  year: number;
  month: number; // 0-indexed (January = 0)
  totalRevenue: number;
  avgOccupancy: number;
  avgADR: number;
  avgRevPAR: number;
  totalArrivals: number;
  totalDepartures: number;
  totalCancellations: number;
}

/**
 * Compute daily metrics for a single date.
 * Works with both ReservationRow (Supabase) and legacy reservation shapes.
 * Canonical fields: check_in / check_out / total_amount / status / created_at
 * Legacy fallbacks:  checkIn  / checkOut  / totalTTC    / status
 */
export function computeDayMetrics(
  reservations: any[],
  dateStr: string,
  totalRoomsCount: number
): DayMetric {
  const dayTs = new Date(dateStr).getTime();

  let occupiedRooms = 0;
  let revenue = 0;
  let arrivals = 0;
  let departures = 0;
  let cancellations = 0;

  for (const r of reservations) {
    // Normalise field names (Supabase snake_case vs legacy camelCase)
    const checkIn: string = r.check_in ?? r.checkIn ?? '';
    const checkOut: string = r.check_out ?? r.checkOut ?? '';
    const amount: number = r.total_amount ?? r.totalTTC ?? 0;
    const status: string = r.status ?? '';

    if (!checkIn || !checkOut) continue;

    const inTs = new Date(checkIn).getTime();
    const outTs = new Date(checkOut).getTime();

    if (isNaN(inTs) || isNaN(outTs)) continue;

    // Reservation is present: check_in <= dateStr < check_out
    const isPresent = inTs <= dayTs && dayTs < outTs;

    if (status === 'cancelled') {
      // Count cancellations by original check-in date
      if (checkIn.startsWith(dateStr)) cancellations++;
      continue;
    }

    if (isPresent) {
      occupiedRooms++;
      revenue += amount;
    }

    // Arrivals: check_in == dateStr
    if (checkIn.startsWith(dateStr)) arrivals++;

    // Departures: check_out == dateStr
    if (checkOut.startsWith(dateStr)) departures++;
  }

  const safeRooms = Math.max(1, totalRoomsCount);
  const adr = occupiedRooms > 0 ? Math.round(revenue / occupiedRooms) : 0;
  const revpar = Math.round(revenue / safeRooms);
  const occupancyRate = Math.min(100, Math.round((occupiedRooms / safeRooms) * 100));

  return {
    dateStr,
    occupiedRooms,
    availableRooms: totalRoomsCount,
    occupancyRate,
    revenue,
    adr,
    revpar,
    arrivals,
    departures,
    cancellations,
  };
}

/**
 * Aggregate daily metrics for every day in a calendar month into a MonthMetric.
 */
export function computeMonthlyKPIs(
  reservations: any[],
  year: number,
  month: number, // 0-indexed
  totalRoomsCount: number
): MonthMetric {
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  let totalRevenue = 0;
  let totalOccSum = 0;
  let totalADRSum = 0;
  let adrDays = 0;
  let totalArrivals = 0;
  let totalDepartures = 0;
  let totalCancellations = 0;

  for (let d = 1; d <= daysInMonth; d++) {
    const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
    const m = computeDayMetrics(reservations, dateStr, totalRoomsCount);
    totalRevenue += m.revenue;
    totalOccSum += m.occupancyRate;
    if (m.adr > 0) { totalADRSum += m.adr; adrDays++; }
    totalArrivals += m.arrivals;
    totalDepartures += m.departures;
    totalCancellations += m.cancellations;
  }

  const avgOccupancy = Math.round(totalOccSum / daysInMonth);
  const avgADR = adrDays > 0 ? Math.round(totalADRSum / adrDays) : 0;
  const avgRevPAR = Math.round(totalRevenue / Math.max(1, totalRoomsCount * daysInMonth));

  return {
    year,
    month,
    totalRevenue,
    avgOccupancy,
    avgADR,
    avgRevPAR,
    totalArrivals,
    totalDepartures,
    totalCancellations,
  };
}

// ─────────────────────────────────────────────────────────────────────────────

export interface ReportKPIs {
  occupancyRate: number;
  adr: number;
  revPar: number;
  totalRevenue: number;
  totalNights: number;
  avgStayLength: number;
}

export const calculateKPIs = (reservations: any[], totalRoomsCount: number, period?: { start: string, end: string }): ReportKPIs => {
  let filtered = reservations.filter(r => r.status !== 'cancelled');
  if (period) {
    filtered = filtered.filter(r => r.checkIn >= period.start && r.checkIn <= period.end);
  }
  
  const totalNights = filtered.reduce((sum, r) => sum + (r.nights || 0), 0);
  const totalRevenue = filtered.reduce((sum, r) => sum + (r.totalTTC || 0), 0);
  
  const occupancyRate = totalRoomsCount > 0 ? (totalNights / (totalRoomsCount * 30)) * 100 : 0; 
  const adr = totalNights > 0 ? totalRevenue / totalNights : 0;
  const revPar = totalRoomsCount > 0 ? totalRevenue / (totalRoomsCount * 30) : 0;
  
  return {
    occupancyRate: Math.min(100, Math.max(0, occupancyRate)),
    adr,
    revPar,
    totalRevenue,
    totalNights,
    avgStayLength: filtered.length > 0 ? totalNights / filtered.length : 0
  };
};

export const getComparisonData = (reservations: any[], totalRoomsCount: number, currentPeriod: { start: string, end: string }) => {
  const currentKpis = calculateKPIs(reservations, totalRoomsCount, currentPeriod);
  
  const lastYearStart = new Date(currentPeriod.start);
  lastYearStart.setFullYear(lastYearStart.getFullYear() - 1);
  const lastYearEnd = new Date(currentPeriod.end);
  lastYearEnd.setFullYear(lastYearEnd.getFullYear() - 1);
  
  // Use YYYY-MM-DD exactly
  const lastYearStartStr = lastYearStart.toISOString().split('T')[0];
  const lastYearEndStr = lastYearEnd.toISOString().split('T')[0];

  const lastYearKpis = calculateKPIs(reservations, totalRoomsCount, { 
    start: lastYearStartStr, 
    end: lastYearEndStr 
  });

  const getDiff = (curr: number, prev: number) => {
    if (prev === 0) return 0;
    return ((curr - prev) / prev) * 100;
  };

  return {
    current: currentKpis,
    previous: lastYearKpis,
    diff: {
      totalRevenue: getDiff(currentKpis.totalRevenue, lastYearKpis.totalRevenue),
      occupancyRate: getDiff(currentKpis.occupancyRate, lastYearKpis.occupancyRate),
      adr: getDiff(currentKpis.adr, lastYearKpis.adr),
      revPar: getDiff(currentKpis.revPar, lastYearKpis.revPar)
    }
  };
};

export const getOccupancyByDay = (reservations: any[], days: number = 30) => {
  const data: Record<string, number> = {};
  const today = new Date();
  
  for (let i = 0; i < days; i++) {
    const d = new Date(today);
    d.setDate(today.getDate() + i);
    const dateStr = d.toISOString().split('T')[0];
    data[dateStr] = 0;
    
    reservations.forEach(r => {
      if (r.checkIn <= dateStr && r.checkOut > dateStr && r.status !== 'cancelled') {
        data[dateStr]++;
      }
    });
  }
  
  return Object.entries(data).map(([date, count]) => ({ date, count }));
};

export const getRevenueByChannel = (reservations: any[]) => {
  const channels: Record<string, number> = {};
  reservations.forEach(r => {
    if (r.status !== 'cancelled') {
      const channel = r.channel || 'Direct';
      channels[channel] = (channels[channel] || 0) + (r.totalTTC || 0);
    }
  });
  return Object.entries(channels).map(([name, value]) => ({ name, value }));
};

export const getRevenueBySegment = (reservations: any[]) => {
  const segments: Record<string, number> = {};
  reservations.forEach(r => {
    if (r.status !== 'cancelled') {
      const segment = r.segment || 'Loisir';
      segments[segment] = (segments[segment] || 0) + (r.totalTTC || 0);
    }
  });
  return Object.entries(segments).map(([name, value]) => ({ name, value }));
};
